defmodule EdgeLinkoutsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :edge_linkouts

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # secure: true in production (config/prod.exs sets :secure_cookies). Compile-time read
  # is correct here: the option list is a compile-time attribute, and prod always serves
  # behind TLS; dev and test keep plain http on localhost working.
  @session_options [
    store: :cookie,
    key: "_edge_linkouts_key",
    signing_salt: "KJqSObnp",
    same_site: "Lax",
    secure: Application.compile_env(:edge_linkouts, :secure_cookies, false)
  ]

  # compress: permessage-deflate on the LiveView websocket. Every diff after the first
  # render travels compressed, which is most of this app's outbound bytes to clients
  # (default is off; verified in phoenix/transports/websocket.ex for 1.8.15).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], compress: true],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :edge_linkouts,
    gzip: not code_reloading?,
    only: EdgeLinkoutsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Liveness first: /healthz must answer before the origin lockdown and without touching
  # anything, so Fly's direct (header-less, plain-HTTP) machine checks pass.
  plug EdgeLinkoutsWeb.HealthCheck

  # Origin lockdown: reject anything that did not come through the Cloudflare zone
  # (the zone adds the shared header via a Transform Rule). Nothing here runs without
  # it, so direct hits on the fly.dev hostname cannot reach the store. Inert unless
  # :origin_check_key is configured (runtime.exs sets it in prod from X_ORIGIN_KEY), so
  # local dev and tests are untouched even if the variable leaks into the shell.
  plug EdgeLinkoutsWeb.OriginCheck

  plug Plug.Parsers,
    # The app has no form POST routes at all (events travel on the LiveView socket), so
    # the parser list is the smallest that still serves the longpoll fallback, and the
    # body limit is tiny. Less accepted input is less attack surface.
    parsers: [:urlencoded],
    pass: ["*/*"],
    length: 64_000

  plug Plug.Head
  plug Plug.Session, @session_options
  plug EdgeLinkoutsWeb.Router
end
