defmodule EdgeLinkoutsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :edge_linkouts

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_edge_linkouts_key",
    signing_salt: "KJqSObnp",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :edge_linkouts,
    gzip: not code_reloading?,
    only: EdgeLinkoutsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Origin lockdown: reject anything that did not come through the Cloudflare zone
  # (the zone adds the shared header via a Transform Rule). Nothing here runs without
  # it, so direct hits on the fly.dev hostname cannot reach the store. Inert unless
  # ORIGIN_CHECK_KEY is set, so local dev and tests are untouched.
  plug EdgeLinkoutsWeb.OriginCheck

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EdgeLinkoutsWeb.Router
end
