package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/glusman-team/edge-linkouts/cli/internal/codec"
)

type rigFlags struct {
	limit     int
	predicate string
	exs       bool
}

func newRigCmd(g *globals) *cobra.Command {
	f := &rigFlags{}
	cmd := &cobra.Command{
		Use:   "rig <edges.ndjson>",
		Short: "Inspect a KGX file and draft a display configuration for it",
		Long: `rig reads a KGX edges file and reports what is actually in it: which predicates
appear, which qualifier slots each one carries, how often, and with what value shapes.

That report is what a display configuration is written from. The legacy configs were
hand-maintained Perl that drifted from the data — fields renamed between releases, slots
dropped, new qualifiers nobody rendered. rig makes the drift visible, and --exs emits a
starter kgs/*.exs with every observed field wired to a template so nothing is silently
ignored.

Nothing is written to storage: rig only reads the file you point it at.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runRig(args[0], f)
		},
	}
	cmd.Flags().IntVar(&f.limit, "limit", 20000, "maximum edges to inspect (0 = all)")
	cmd.Flags().StringVar(&f.predicate, "predicate", "", "restrict to one predicate")
	cmd.Flags().BoolVar(&f.exs, "exs", false, "emit a starter display config instead of a report")
	return cmd
}

// fieldStats is what rig accumulates per predicate.
type fieldStats struct {
	edges   int
	present map[string]int
	lists   map[string]int
	example map[string]string
}

func runRig(path string, f *rigFlags) error {
	fh, err := os.Open(path)
	if err != nil {
		return err
	}
	// Read-only handle: nothing is buffered, so a Close failure cannot lose data.
	defer func() { _ = fh.Close() }()

	sc := bufio.NewScanner(fh)
	sc.Buffer(make([]byte, 0, 64*1024), 64*1024*1024)
	stats := map[string]*fieldStats{}
	predicates := map[string]int{}
	seen, malformed := 0, 0
	for sc.Scan() {
		raw := sc.Bytes()
		if len(raw) == 0 {
			continue
		}
		if f.limit > 0 && seen >= f.limit {
			break
		}
		// Lenient parse: rig inspects other people's data, so a null or an odd shape is a
		// finding to report, not a reason to abort.
		doc, err := codec.ParseLenient(raw)
		if err != nil {
			malformed++
			continue
		}
		seen++
		predicate, _ := doc["predicate"].(string)
		if predicate == "" {
			predicate = "(missing)"
		}
		if f.predicate != "" && predicate != f.predicate {
			continue
		}
		predicates[predicate]++
		st, ok := stats[predicate]
		if !ok {
			st = &fieldStats{present: map[string]int{}, lists: map[string]int{}, example: map[string]string{}}
			stats[predicate] = st
		}
		st.edges++
		for k, v := range doc {
			if codec.Nullish(v) {
				continue
			}
			st.present[k]++
			if list, ok := v.([]any); ok {
				st.lists[k] += len(list)
			}
			if _, have := st.example[k]; !have {
				st.example[k] = exampleOf(v)
			}
		}
	}
	if err := sc.Err(); err != nil {
		return err
	}
	if seen == 0 {
		return fmt.Errorf("%s contained no usable KGX edge records", path)
	}
	if f.exs {
		return emitConfig(path, stats)
	}
	return printReport(path, seen, malformed, predicates, stats)
}

func printReport(path string, seen, malformed int, predicates map[string]int, stats map[string]*fieldStats) error {
	printf("%s: %d edges inspected", path, seen)
	if malformed > 0 {
		printf(" (%d lines unparseable)", malformed)
	}
	println("")
	names := make([]string, 0, len(predicates))
	for p := range predicates {
		names = append(names, p)
	}
	sort.Slice(names, func(i, j int) bool { return predicates[names[i]] > predicates[names[j]] })
	for _, p := range names {
		st := stats[p]
		printf("\n%s  (%d edges)\n", p, predicates[p])
		fields := make([]string, 0, len(st.present))
		for k := range st.present {
			fields = append(fields, k)
		}
		sort.Slice(fields, func(i, j int) bool { return st.present[fields[i]] > st.present[fields[j]] })
		for _, k := range fields {
			n := st.present[k]
			line := fmt.Sprintf("  %-34s %6d  %5.1f%%", k, n, 100*float64(n)/float64(st.edges))
			if total, isList := st.lists[k]; isList {
				line += fmt.Sprintf("  list, %.0f items/edge", float64(total)/float64(n))
			}
			line += "  e.g. " + st.example[k]
			println(line)
		}
	}
	printf("\n%d predicates; fields present on under 1%% of edges are usually release noise\n", len(names))
	return nil
}

// emitConfig writes a starter kgs/*.exs so a new KG starts with every observed field rendered.
func emitConfig(path string, stats map[string]*fieldStats) error {
	predicates := make([]string, 0, len(stats))
	for p := range stats {
		predicates = append(predicates, p)
	}
	sort.Strings(predicates)
	printf(`%% Generated by linkouts rig from %s
%% Every observed field is listed so nothing is silently dropped; replace the :text templates
%% with real prose, then drop fields that should not be displayed.
%%{
  name: "TODO",
  display_name: "TODO",
  version_scope: %%{},
  predicates: %%{
`, path)
	for _, p := range predicates {
		st := stats[p]
		fields := make([]string, 0, len(st.present))
		for k := range st.present {
			fields = append(fields, k)
		}
		sort.Strings(fields)
		printf("    %s => %%{\n", quoteKey(p))
		println(`      text: "TODO: describe this assertion",`)
		printf("      fields: [\n")
		for _, k := range fields {
			printf("        %s: %%{label: %s},\n", atomKey(k), quoteKey(humanize(k)))
		}
		printf("      ]\n    },\n")
	}
	println("  }\n}")
	return nil
}

func exampleOf(v any) string {
	switch t := v.(type) {
	case string:
		return truncateExample(t)
	case []any:
		if len(t) == 0 {
			return "[]"
		}
		return fmt.Sprintf("[%s, …%d]", truncateExample(fmt.Sprint(t[0])), len(t))
	default:
		return truncateExample(fmt.Sprint(t))
	}
}

func truncateExample(s string) string {
	const max = 48
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) <= max {
		return s
	}
	return s[:max] + "…"
}

func humanize(k string) string {
	return strings.ToUpper(k[:1]) + strings.ReplaceAll(k[1:], "_", " ")
}

// atomKey renders a field name as an Elixir atom when it is a valid one, quoted otherwise.
func atomKey(k string) string {
	if k == "" {
		return `:""`
	}
	for i, r := range k {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9' && i > 0, r == '_' && i > 0:
		case r >= 'A' && r <= 'Z':
			return ":" + quoteKey(k)
		default:
			return ":" + quoteKey(k)
		}
	}
	if k[0] >= '0' && k[0] <= '9' {
		return ":" + quoteKey(k)
	}
	return k + ":"
}

func quoteKey(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }
