defmodule EdgeLinkoutsWeb.EdgeLiveTest do
  use EdgeLinkoutsWeb.ConnCase, async: false

  import Phoenix.LiveViewTest

  alias EdgeLinkouts.Codec
  alias EdgeLinkouts.{Cosmos, Dedupe}
  alias EdgeLinkoutsWeb.Fixtures

  @v1 Fixtures.v1()
  @v2 Fixtures.v2()

  # The global Fake (started by the supervision tree in test) is a singleton, so every
  # test here is serial; each one reseeds it from the committed contract fixtures.
  setup do
    Cosmos.Fake.reset()
    Cosmos.Fake.seed(Fixtures.docs())

    %{id: Fixtures.first_edge_id()}
  end

  describe "the linkout page" do
    test "renders the sentence, relationship line and evidence paragraph at both stored versions",
         %{
           id: id
         } do
      for version <- [@v1, @v2] do
        doc = Fixtures.resolved(Fixtures.edge_doc(id), version)
        {:ok, _view, html} = live(build_conn(), "/edges/#{id}?version=#{version}")

        assert html =~ "This relationship states that"
        assert html =~ doc["subject_name"]
        assert html =~ doc["object_name"]

        # The text relationship line carries both names and both CURIEs — the claim in
        # prose, no "biolink:" prefix, no underscores. Each CURIE sits behind a "curie"
        # chip rather than in parentheses, revealed in place by the button.
        assert html =~ "edge-relation"
        assert html =~ doc["subject"]
        assert html =~ doc["object"]
        assert html =~ ~s(data-more="curie")
        refute html =~ "(#{doc["subject"]})"
        refute html =~ "(#{doc["object"]})"

        # The footnote paragraph carries the DailyMed search sentence on its own, beneath the
        # evidence paragraph, not inside it.
        assert html =~ ~s(class="edge-footnote")
        assert html =~ "Try searching DailyMed"
        refute html =~ ~s(edge-evidence">\s*Try searching)

        # The first paragraph ends with the provenance, then names the integrator (linked to
        # its registry page) and its supporting sources, as prose: no field-name label anywhere.
        assert html =~ "was generated by"

        assert html =~
                 ~s(href="https://biolink.github.io/information-resource-registry/resources/drugapprovals-kp/")

        assert html =~ ", which integrates"
        refute html =~ ~s(Assertion method)
        refute html =~ "agent_type is"
      end
    end

    test "a release without a known error renders no notice", %{conn: conn, id: id} do
      # The config currently declares no known errors: 1.16.0 (whose applied-to-treat edges
      # misdisplayed regulatory approvals) was purged and the defect is fixed in 1.23.3. The
      # notice's matching logic stays covered in display_test; here the page must simply not
      # render it.
      for version <- [@v1, @v2] do
        {:ok, _view, html} = live(conn, "/edges/#{id}?version=#{version}")

        refute html =~ "edge-known-error"
        refute html =~ "Known issue in release"
      end
    end

    test "crowded approvals and SPL lists fold inline behind a show-more chip", %{conn: _conn} do
      # A long list — dozens of ANDA numbers on one stored edge — shows its first few items in
      # the sentence and folds the rest behind a chip in that very spot, not into a section of
      # its own. The exact ids stay on the page, one click behind the disclosure.
      {id, version} = crowded_edge()
      {:ok, _view, html} = live(build_conn(), "/edges/#{id}?version=#{version}")

      assert html =~ ~s(class="linkout-more")
      assert html =~ ~r/Show \d+ more/
      # The rest renders collapsed in the markup; the button reveals it (assets/js/app.js).
      assert html =~ ~s(class="linkout-more-rest" hidden)
      assert html =~ "https://fda.report/applications/"

      # The footnote sentence stays in its own paragraph, unaffected by the folds.
      assert html =~ "Try searching DailyMed"
    end

    defp crowded_edge do
      Fixtures.edge_docs()
      |> Enum.flat_map(fn doc ->
        for v <- [@v1, @v2],
            resolved = Fixtures.resolved(doc, v),
            length(approvals_of(resolved)) + length(resolved["publications"] || []) > 5 do
          {doc["id"], v}
        end
      end)
      |> hd()
    end

    defp approvals_of(resolved),
      do: resolved["regulatory_approvals"] || resolved["FDA_regulatory_approvals"] || []

    test "a full page view, static render plus connected mount, costs one backend read", %{
      conn: conn,
      id: id
    } do
      # The test env runs the shared Dedupe with its result cache off, so tests cannot leak
      # documents into each other. Turn it on here to check what production does. Without the
      # cache this was two reads per page view, because the two mounts are sequential and
      # coalescing alone cannot merge them.
      # The cleanup must clear the table as well as restore the ttl. Restoring the ttl alone leaves
      # this test's cached document behind, and the next test reads it instead of the Fake.
      # Seed 92193 caught that. The ExUnit case is async: false, so nothing else runs meanwhile.
      Dedupe.clear()
      :sys.replace_state(Dedupe, &%{&1 | ttl_ms: 30_000})

      on_exit(fn ->
        :sys.replace_state(Dedupe, &%{&1 | ttl_ms: 0})
        Dedupe.clear()
      end)

      {:ok, _view, _html} = live(conn, "/edges/#{id}")

      assert Cosmos.Fake.calls() == [{:get_edge, id}]
    end

    test "switching ?version selects that version without a second backend read", %{
      conn: conn,
      id: id
    } do
      {:ok, view, html} = live(conn, "/edges/#{id}")

      # live/2 mounts twice (static render, then connected). With the result cache off, as it
      # is in tests, that is two reads; the test above covers the production count. The
      # invariant here is that switching the version adds nothing, because the blob in the
      # assigns already holds every stored version.
      calls_after_load = Cosmos.Fake.calls()
      assert calls_after_load != []
      assert Enum.all?(calls_after_load, &match?({:get_edge, ^id}, &1))

      # The switcher links to every stored version. A canonical key carries the infores
      # scheme's colon, which a rendered href percent-encodes.
      assert html =~ "?version=" <> URI.encode_www_form(@v1)
      assert html =~ "?version=" <> URI.encode_www_form(@v2)

      # Patching is exactly what a switcher link does.
      render_patch(view, "/edges/#{id}?version=#{@v1}")

      assert Cosmos.Fake.calls() == calls_after_load
      assert render(view) =~ "aria-current=\"page\""
      # The timeline marks the selected version by its release number, not the full key.
      assert render(view) =~ "1.11.2"
    end

    test "an unknown id answers HTTP 404 with the not-found copy", %{conn: conn} do
      # The LiveView raises EdgeNotFound (plug_status 404); the endpoint renders the 404
      # page with that status and then re-raises, which is Phoenix's behaviour for every
      # rendered error. The response body is asserted end to end via the download
      # controller (same 404 page) and the curl check in the verification run.
      raised =
        assert_raise EdgeLinkoutsWeb.EdgeNotFound, fn ->
          get(conn, "/edges/00000000-0000-0000-0000-000000000000")
        end

      assert raised.plug_status == 404
      assert raised.message =~ "no edge with id"
    end

    # Both ways the transport refuses for capacity: the local RU budget (checked before the call)
    # and Cosmos's own 429 after the single retry. Each must read as "retry", not as a store outage,
    # which is what the page said before Edges.read/2 mapped them.
    for {label, reason} <- [
          {"the local RU budget", :budget_exhausted},
          {"Cosmos 429 after the retry", {:throttled, 250}}
        ] do
      test "#{label} renders the retry copy, not an error term", %{conn: conn, id: id} do
        # live/2 mounts twice (static render, then the connected process), so queue the
        # refusal for both reads.
        Cosmos.Fake.queue_error(unquote(Macro.escape(reason)))
        Cosmos.Fake.queue_error(unquote(Macro.escape(reason)))

        {:ok, view, html} = live(conn, "/edges/#{id}")

        assert html =~ "Rate limited"
        assert html =~ "Retry"
        refute html =~ "could not be reached"
        refute html =~ "{:error"
        refute html =~ "budget_exhausted"
        refute html =~ "throttled"

        # Once reads are admitted again, the retry event loads the page in place.
        render_click(view, "retry", %{})
        assert render(view) =~ "This relationship states that"
      end
    end

    test "a store outage says so, distinct from rate limiting", %{conn: conn, id: id} do
      Cosmos.Fake.queue_error({:http, 503, "unavailable"})
      Cosmos.Fake.queue_error({:http, 503, "unavailable"})

      {:ok, _view, html} = live(conn, "/edges/#{id}")

      assert html =~ "did not answer"
      refute html =~ "Rate limited"
      refute html =~ "503"
    end

    test "a corrupt blob names the reason instead of a generic failure", %{conn: conn} do
      Cosmos.Fake.seed(%{"id" => "corrupt-edge", "b" => "!!! not base64 !!!"})

      {:ok, _view, html} = live(conn, "/edges/corrupt-edge")

      assert html =~ "Corrupt stored document"
      assert html =~ "not valid base64"
      refute html =~ "{:error"
    end

    test "an unknown ?version names it in the corrupt copy", %{conn: conn, id: id} do
      {:ok, _view, html} = live(conn, "/edges/#{id}?version=nope-9.9.9")

      assert html =~ "Corrupt stored document"
      assert html =~ "does not store a version"
      assert html =~ "nope-9.9.9"
    end

    test "a hostile subject_name appears escaped and never as a live tag", %{conn: conn} do
      id = "22222222-2222-4222-8222-222222222222"
      base = Fixtures.resolved(Fixtures.edge_doc(Fixtures.first_edge_id()), @v1)
      hostile = Map.put(base, "subject_name", "<script>alert(1)</script>")

      Cosmos.Fake.seed(Fixtures.stored(id, %{@v1 => hostile}))

      {:ok, _view, html} = live(conn, "/edges/#{id}")

      assert html =~ "&lt;script&gt;alert(1)&lt;/script&gt;"
      refute html =~ "<script>alert(1)</script>"
    end
  end

  describe "the version diff" do
    test "shows an added field, a removed field and a changed value", %{conn: conn} do
      id = "33333333-3333-4333-8333-333333333333"

      v1 = %{
        "id" => id,
        "subject" => "CHEBI:64019",
        "subject_name" => "aspirin",
        "object" => "MONDO:0000418",
        "object_name" => "ischemic stroke",
        "predicate" => "biolink:treats",
        "number_of_cases" => 12,
        "knowledge_level" => "assertion",
        "publications" => ["PMID:1"]
      }

      v2 = %{
        "$t" => @v1,
        "$set" => %{"number_of_cases" => 42},
        "$add" => %{"publications" => ["PMID:2"]},
        "$del" => ["knowledge_level"]
      }

      Cosmos.Fake.seed(Fixtures.stored(id, %{@v1 => v1, @v2 => v2}))

      {:ok, _view, html} = live(conn, "/edges/#{id}")

      assert html =~ "differ between"
      assert html =~ "diff-line-added"
      assert html =~ "diff-line-removed"

      # Changed value: old and new, both visible, labelled rather than just coloured.
      assert html =~ ~s(class="diff-old")
      assert html =~ ">12</code>"
      assert html =~ ">42</code>"

      # Added list element and removed field, each in its reader's vocabulary.
      assert html =~ "PMID:2"
      assert html =~ "Knowledge level"
      assert html =~ "assertion"
    end

    test "a single-version page says there is nothing earlier to compare", %{conn: conn} do
      id = "44444444-4444-4444-8444-444444444444"

      v1 = %{
        "id" => id,
        "subject" => "CHEBI:64019",
        "subject_name" => "aspirin",
        "object" => "MONDO:0000418",
        "object_name" => "ischemic stroke",
        "predicate" => "biolink:treats"
      }

      Cosmos.Fake.seed(Fixtures.stored(id, %{@v1 => v1}))

      {:ok, _view, html} = live(conn, "/edges/#{id}")

      assert html =~ "nothing earlier to compare"
    end
  end

  describe "the KGX download link" do
    test "the feedback link carries the current permalink", %{conn: conn, id: id} do
      {:ok, _view, html} = live(conn, "/edges/#{id}")

      # The test conn's host is www.example.com.
      permalink = "http://www.example.com/edges/#{id}"
      assert html =~ URI.encode_www_form(permalink)
    end
  end

  describe "the KG-scoped random button" do
    test "on an edge page the header button stays inside that graph and release", %{
      conn: conn,
      id: id
    } do
      {:ok, _view, html} = live(conn, "/edges/#{id}")

      # A reader looking at one graph who asks for a random edge expects another edge from
      # that graph, in the release they are reading (newest when the URL names none). A
      # button that could leave the store's current subject is a button nobody can trust, so
      # the scoping is worth an assertion of its own.
      assert html =~ ~s(href="/drugapprovals-kp/random?version=1.16.0")
      refute html =~ ~s(href="/drugapprovals-kp/random")
      refute html =~ ~s(href="/random")
    end

    test "a random click inside one release stays inside it, and switching versions re-pins", %{
      conn: conn,
      id: id
    } do
      {:ok, view, html} = live(conn, "/edges/#{id}?version=#{@v1}")

      # The pin is the release in the URL: random draws from exactly what the reader sees.
      assert html =~ ~s(href="/drugapprovals-kp/random?version=1.11.2")

      # Switching versions re-pins the button, so the next random click follows the reader.
      refute render_patch(view, "/edges/#{id}?version=#{@v2}") =~
               ~s(href="/drugapprovals-kp/random?version=1.11.2")

      assert render_patch(view, "/edges/#{id}?version=#{@v2}") =~
               ~s(href="/drugapprovals-kp/random?version=1.16.0")
    end

    test "the graph's name links to the same scoped pick", %{conn: conn, id: id} do
      {:ok, _view, html} = live(conn, "/edges/#{id}")

      assert html =~ ~s(class="kg-link")
      assert html =~ "DrugApprovals KP"

      # The source keeps its own external link beside the name, which is what frees the name
      # to stay inside this app.
      assert html =~
               "https://github.com/NCATSTranslator/Translator-All/wiki/Multiomics-Drug-Approvals-KP"
    end

    test "a graph with no display config still scopes the button", %{conn: conn} do
      id = "00000000-0000-4000-8000-0000000000ff"

      Cosmos.Fake.seed(
        Fixtures.stored(id, %{
          "infores:unconfigured-kp-1.0.0" => %{
            "id" => id,
            "subject" => "a",
            "predicate" => "biolink:related_to",
            "object" => "b"
          }
        })
      )

      {:ok, _view, html} = live(conn, "/edges/#{id}")

      assert html =~ ~s(href="/unconfigured-kp/random?version=1.0.0")
      # With no config there is no display name, so the canonical name is what a reader gets.
      assert html =~ "infores:unconfigured-kp"
    end

    test "a page with no readable document keeps the button global", %{conn: conn} do
      id = "00000000-0000-4000-8000-0000000000fe"
      Cosmos.Fake.seed(%{"id" => id, "b" => "not-a-frame"})

      {:ok, _view, html} = live(conn, "/edges/#{id}")

      # There is no graph to scope to until a document has been read, so the button keeps its
      # whole-store meaning instead of linking to a slug nobody has established.
      assert html =~ ~s(href="/random")
    end
  end

  # The downloaded bytes must be identical to what Codec would canonicalise, so this
  # helper is shared with the controller test.
  def canonical_at(id, key),
    do: Fixtures.edge_doc(id) |> Fixtures.resolved(key) |> Codec.canonical_binary()
end
