defmodule EdgeLinkouts.ContractTest do
  @moduledoc """
  The cross-language contract.

  These fixtures are written by the Go CLI (`make contract`) and read here by the Elixir codec.
  Nothing in this file is generated by Elixir, so a failure means the two implementations
  disagree — which is the one class of bug that cannot be caught by testing either side alone.

  The strongest assertion here is `test "Elixir re-encodes Go's canonical bytes exactly"`: the
  bytes inside each zstd frame are the CLI's canonical JSON, so decoding and re-encoding them
  must reproduce them byte for byte. Escaping, key order, and number formatting all have to
  match, or KGX downloads and any future hash comparison would drift between languages.
  """
  use ExUnit.Case, async: true

  alias EdgeLinkouts.{Codec, Cosmos}

  @fixtures Path.expand("fixtures/contract", __DIR__)
  @docs Path.join(@fixtures, "docs.ndjson")
  @drift Path.join(@fixtures, "drift.ndjson")
  @unresolvable Path.join(@fixtures, "unresolvable.ndjson")

  # The canonical load keys, in the infores form the wiki lists the graph under, and the slug
  # that is stored on documents and used in pool ids and URLs.
  @slug "drugapprovals-kp"
  @v1 "infores:drugapprovals-kp-1.11.2"
  @v2 "infores:drugapprovals-kp-1.16.0"
  @index_id "__random_pool__"

  setup_all do
    for path <- [@docs, @drift, @unresolvable] do
      unless File.exists?(path) do
        flunk("""
        missing contract fixture #{path}

        These are written by the Go CLI, not by Elixir. Regenerate them with:

            make contract-test
        """)
      end
    end

    {:ok,
     docs: read_docs(@docs), drift: read_docs(@drift), unresolvable: read_docs(@unresolvable)}
  end

  # The file backend stores one JSON object per line: id, base64 frame, optional dictionary id.
  defp read_docs(path) do
    path
    |> File.stream!()
    |> Stream.map(&String.trim/1)
    |> Stream.reject(&(&1 == ""))
    |> Enum.map(&JSON.decode!/1)
  end

  # A fixture file holds two kinds of document: edge blobs and the reserved pool documents
  # behind /random. The same rule the CLI uses (`cosmos.IsReservedID`) splits them.
  defp edge_docs(docs), do: Enum.reject(docs, &Cosmos.reserved_id?(&1["id"]))

  defp reserved_doc(docs, id), do: Enum.find(docs, &(&1["id"] == id))

  defp frame_body(%{"b" => _b64, "d" => dict_id}) when not is_nil(dict_id) do
    # A dictionary-compressed fixture would need web/priv/zstd; the committed contract
    # fixtures are deliberately dictionary-free so this test has no binary dependency.
    flunk(
      "contract fixture was written with dictionary #{inspect(dict_id)}; regenerate with `make contract`"
    )
  end

  defp frame_body(%{"b" => b64}) do
    {:ok, frame} = Base.decode64(b64)
    frame |> :zstd.decompress() |> IO.iodata_to_binary()
  end

  describe "stored documents" do
    test "every fixture document is readable and carries an id and a frame", %{docs: docs} do
      assert length(docs) == 9,
             "expected 6 edges plus one pool per release plus the index, got #{length(docs)}"

      for doc <- docs do
        assert is_binary(doc["id"]) and doc["id"] != ""
        assert is_binary(doc["b"]) and doc["b"] != ""

        assert Map.keys(doc) -- ["id", "b", "d", "k"] == [],
               "unexpected stored fields: #{inspect(doc)}"
      end

      # `k` is on edge documents and on nothing else: a pool belongs to a release by its id,
      # and repeating the slug inside it would be bytes that answer no question.
      for doc <- edge_docs(docs) do
        assert doc["k"] == @slug, "#{doc["id"]} carries k=#{inspect(doc["k"])}"
      end

      for doc <- docs, Cosmos.reserved_id?(doc["id"]) do
        refute Map.has_key?(doc, "k"), "#{doc["id"]} should not carry a k field"
      end
    end

    test "the pool index lists every release with its true edge count", %{docs: docs} do
      index_doc = reserved_doc(docs, @index_id)
      assert index_doc, "no #{@index_id} document, so /random cannot find a release to pick from"

      {:ok, index} = Codec.decode_pool_index(index_doc["b"])
      releases = index[@slug]
      assert Map.keys(releases) |> Enum.sort() == ["1.11.2", "1.16.0"]

      # The counts are what a weighted pick runs on, so they must be the real ones: an
      # over-count would make /random favour a release it does not represent.
      assert length(edge_docs(docs)) == 6
      assert releases["1.11.2"].edges == 6
      assert releases["1.16.0"].edges == 6
      assert releases["1.16.0"].sampled == 6
      # The fixture clock is pinned by `make contract`, so regeneration stays byte-stable.
      assert releases["1.16.0"].sampled_at == "2026-01-01T00:00:00Z"
    end

    test "each release's pool lists only ids that exist", %{docs: docs} do
      edge_ids = docs |> edge_docs() |> Enum.map(& &1["id"]) |> MapSet.new()

      for {label, key} <- [{"1.11.2", @v1}, {"1.16.0", @v2}] do
        id = Cosmos.pool_doc_id(@slug, label)
        pool_doc = reserved_doc(docs, id)
        assert pool_doc, "no #{id} document, so /#{@slug}/random?version=#{label} cannot work"

        {:ok, pool} = Codec.decode_pool(pool_doc["b"])
        assert is_list(pool.ids) and pool.ids != []
        assert pool.key == key, "the pool should report the key it was loaded under"

        for edge_id <- pool.ids do
          assert MapSet.member?(edge_ids, edge_id), "pool references #{edge_id}, not stored"
        end

        assert Enum.uniq(pool.ids) == pool.ids, "duplicate ids would bias /random"
        assert Enum.sort(pool.ids) == pool.ids, "the CLI sorts a reservoir, so bytes are stable"
      end
    end

    test "every edge decodes, resolves, and is null-free", %{docs: docs} do
      for doc <- edge_docs(docs) do
        assert {:ok, blob} = Codec.decode(doc["b"]), "failed to decode #{doc["id"]}"
        assert Codec.versions(blob) == [@v1, @v2], "unexpected versions for #{doc["id"]}"

        for version <- Codec.versions(blob) do
          assert {:ok, resolved} = Codec.resolve(blob, version)
          assert :ok = Codec.reject_nulls(resolved), "#{doc["id"]} #{version} contains a null"
          assert resolved["id"] == doc["id"], "the document id must match the edge's KGX id"

          for field <- ["subject", "object", "predicate"] do
            assert is_binary(resolved[field]), "#{doc["id"]} #{version} lost #{field}"
          end
        end
      end
    end

    test "the join attached node-side names", %{docs: docs} do
      # This is the whole reason the CLI joins against nodes.ndjson: names and categories are
      # not on KGX edges, and the display configs need them to pick a template.
      for doc <- edge_docs(docs) do
        {:ok, blob} = Codec.decode(doc["b"])
        {:ok, resolved} = Codec.resolve(blob, @v1)

        assert is_binary(resolved["subject_name"]) and resolved["subject_name"] != "",
               "#{doc["id"]} has no subject_name"

        assert is_binary(resolved["object_name"]) and resolved["object_name"] != "",
               "#{doc["id"]} has no object_name"

        assert is_list(resolved["subject_category"]), "#{doc["id"]} has no subject_category"
      end
    end

    test "the second version is stored as a delta against the first", %{docs: docs} do
      # If the CLI stored both versions in full, storage would double for a handful of changed
      # fields. This is the assertion that keeps that from regressing silently.
      for doc <- edge_docs(docs) do
        raw = doc["b"] |> Base.decode64!() |> :zstd.decompress() |> IO.iodata_to_binary()
        payload = JSON.decode!(raw)
        v2 = payload["versions"][@v2]

        assert is_map(v2), "#{doc["id"]} has no #{@v2}"
        assert v2["$t"] == @v1, "#{doc["id"]}: #{@v2} should target #{@v1}, got #{inspect(v2)}"
        refute Map.has_key?(v2, "subject"), "a delta should not restate unchanged fields"
      end
    end

    test "Elixir re-encodes Go's canonical bytes exactly", %{docs: docs, drift: drift} do
      # The frame content IS the CLI's canonical output. Re-encoding the decoded term must
      # reproduce it byte for byte: same key order, same escaping, same number text.
      for doc <- docs ++ drift do
        raw = frame_body(doc)
        decoded = JSON.decode!(raw)

        assert Codec.canonical_binary(decoded) == raw, """
        canonical re-encode differs for #{doc["id"]}

        This means the two languages disagree on key order, escaping, or number formatting,
        so a KGX download would not match what the CLI stored. Find the first difference:

            iex> a = Codec.canonical_binary(JSON.decode!(raw))
            iex> Enum.find_index(0..byte_size(raw), fn i -> binary_part(a, i, 1) != binary_part(raw, i, 1) end)
        """
      end
    end

    test "the first version's stored payload is exactly its resolved document", %{docs: docs} do
      # v1 is stored in full, so resolving it must return the stored payload unchanged. If this
      # ever differs, resolve is inventing or dropping fields.
      for doc <- edge_docs(docs) do
        payload = doc |> frame_body() |> JSON.decode!()
        stored = payload["versions"][@v1]

        {:ok, blob} = Codec.decode(doc["b"])
        {:ok, resolved} = Codec.resolve(blob, @v1)

        assert Codec.canonical_binary(resolved) == Codec.canonical_binary(stored)
      end
    end
  end

  describe "renamed fields across releases" do
    test "the newer release's field name is what arrives", %{drift: drift} do
      # Measured drift in DAKP: FDA_regulatory_approvals in 1.11.2 became regulatory_approvals
      # in 1.16.0. A display config that only knows the old name would render nothing, which
      # is why version-scoped aliases exist.
      assert drift != [], "the drift fixture is empty"

      renamed =
        for doc <- edge_docs(drift),
            {:ok, blob} = Codec.decode(doc["b"]),
            version <- Codec.versions(blob),
            {:ok, resolved} = Codec.resolve(blob, version),
            do: resolved

      assert Enum.any?(renamed, &Map.has_key?(&1, "regulatory_approvals")),
             "no drift edge carries regulatory_approvals: #{inspect(Enum.map(renamed, &Map.keys/1))}"

      for doc <- renamed do
        assert :ok = Codec.reject_nulls(doc)
      end
    end
  end

  describe "unresolvable nodes" do
    test "names are absent, never null", %{unresolvable: unresolvable} do
      assert length(unresolvable) >= 2

      for doc <- edge_docs(unresolvable) do
        {:ok, blob} = Codec.decode(doc["b"])
        {:ok, resolved} = Codec.resolve(blob, Codec.newest(blob))

        for field <- ["subject_name", "object_name"] do
          refute Map.has_key?(resolved, field),
                 "#{doc["id"]} stored #{field} for a node that does not exist; it must be absent, not null"
        end

        assert :ok = Codec.reject_nulls(resolved)
      end
    end
  end
end
